### ISSUE TITLE
scale input/output numeric values?

### ISSUE THREAD

**Issue by vr25** [YangLinyi/HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction#10]
Hi,

I tried to go through your code but I didn't find anything related to scaling the values.

Since the different numeric features have different scales, do you scale the input and output values using MinMaxScaler? If yes, do you do inverse_transform while predicting on the test set and computing mse?

Thanks!

**Comment by YangLinyi** [comment]
Hi,

The value of the dot product will be scaled before feeding into softmax. This is proposed in the original transformer model in order to avoid the vanishing gradient problem.

For example:
```
    q = np.random.randn(dim)
    ks = np.random.randn(time_steps, dim)
    x = np.sum(q * ks, axis=1) / scale  # x.shape = (time_steps,) 
    y = softmax(x)
```

Hope it will help you get a full understanding of our work.

**Comment by vr25** [comment]
Hi Linyi,

Thank you for your prompt reply.

My question is slightly different. I meant the financial features like price/earnings, volatility, etc which have different scales (somewhere around 24 and 3 respectively). So when they are concatenated with the document vectors (with weights between -1 and 1) there is quite a difference between all these values. So how to make sure if they are on the same scale?
