### ISSUE TITLE
reproducibility 

### ISSUE THREAD

**Issue by hpataci** [YangLinyi/HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction#11]
Hello there,
I have been working on your Github repo "HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction" to reproduce the results mentioned in your paper but I had some issues.

This is a gentle request to provide a README file with clear instructions on how to run the code especially:

1. How to obtain the .npy features files?
2. What columns to use from the raw data file and how to arrange the data obtained using BERT?
3. What are the shapes of the 2 labels files "volitility_following_3days.npy" and "volitility_single_3days.npy"?

And any other information/instructions you think are useful to run the code.

Thank you in advance, your help is much appreciated!

**Comment by ahmed-hassan19** [comment]
Yes, please! I have the same request.

**Comment by dl14666** [comment]
Dear Linyi Yang please can you reply, thanks!

**Comment by YangLinyi** [comment]
Because the sentence-level embedding should be encoded by a pre-trained language model like BERT first. The illustration has been shown on the sentence-level encoder folder.

Hope it helps.
