### ISSUE TITLE
Finding data files for Experiment_HTML_Multimodal.ipynb

### ISSUE THREAD

**Issue by jonsaadfalcon** [YangLinyi/HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction#4]
Hello, I am having issues locating the data files necessary for running the Experiment_HTML_Multimodal.ipynb notebook. I downloaded all the suggested data files and dependencies but right now, I can't seem to find several of the data files, including: /audio_data/audio_features.npy, /audio_data/audio_features_3.npy, /text_data/doc_embs_padding_large.npy, and /text_data/3days_embds_padding_large.npy. Where can I find these files or how can I produce them?

**Comment by YangLinyi** [comment]
Hi Jon,

Limited by the data size, we do not upload it to the project yet. However, we describe how to generate these files based on the raw text/audio (Two methods provided in the Data folder). For the audio feature part, we use the data from https://github.com/GeminiLn/EarningsCall_Dataset [ACL, 19] directly. We get the audio feature data by emailing the authors of [ACL,19], but we do not get permission to put it publicly online.

Hope it can resolve your problems.

Best regards,
Linyi

**Comment by jonsaadfalcon** [comment]
Hi Linyi,

Thanks for the help. I've got the raw text and raw audio but how do I convert them into the .npy files needed for the Python notebooks? I can't seem to find any methods or functions in the data folder for converting them into these files.

Regards,

Jon

**Comment by YangLinyi** [comment]
Hi Jon,

1) For encoding the raw text:
Please find this project: https://github.com/hanxiao/bert-as-service

It allows you to encode each sentence to a sentence embedding, then it could be easily padded to shape an embedding file with .npy format.

2) For generating the audio features:
We have tried to use the script code of Praat, it can generate the 27 low-level audio features as mentioned in the report of [ACL,19]. Also, you can try to email authors to get the feature data directly.

Thanks and regards,
Linyi

**Comment by jonsaadfalcon** [comment]
Hi Linyi,

Thank you for the resources! They are very helpful. I have an additional question about the raw text to embedding process. For the generated .npy files, does each row hold a single earnings call or a single sentence from an earnings call?

Regards,
Jon

**Comment by YangLinyi** [comment]
Hi Jon,

The answer is that each row holds a single sentence with a dynamic sentence length.

While when you padding it to shape the document embedding, it should be padded into the number of the maximum sentences in an earnings call among all documents, which is set to 520 in this work. Hence, the shape of a given document embedding should be [520 (Max_Sentence_Number), 1024 (Embedding_Size)].

Best

**Comment by jonsaadfalcon** [comment]
Hi Linyi,

I have a followup question about the volatility labels. Since the .npy files for the text and audio files contain a sentence in every row, how do I organize the volatility labels .npy file since each label will correspond to a different range of rows?

Regards,
Jon
