### ISSUE TITLE
Calculating Stock Volatility Values

### ISSUE THREAD

**Issue by jonsaadfalcon** [YangLinyi/HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction#5]
In section 3 of the paper, it discusses how to calculate the volatility values. However, is there any dataset with the stock volatility values calculated for the [ACL 19] dataset? If not, how can I generate it?

**Comment by YangLinyi** [comment]
Please refer to the closed issue#3 "Could you also upload the stock data for different time windows?"

Details can be found at #3 

Thanks.
