### ISSUE TITLE
Error Running Experiments_HTML_Multimodal

### ISSUE THREAD

**Issue by jonsaadfalcon** [YangLinyi/HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction#6]
When I try running Experiments_HTML_Multimodal, I get the following error when running the cell titled "3 days validation set":

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-33-9299f1370a87> in <module>
     31         })
     32 
---> 33         evaluation = run_gpu.go(args)
     34         print('Results in alpha = ',i)
     35         print(evaluation)

~/Documents/HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction/Model/Experiments/run_gpu.py in go(arg)
    120         model.train(True)
    121 
--> 122         for i, data in enumerate(trainloader):
    123             # learning rate warmup
    124             # - we linearly increase the learning rate from 10e-10 to arg.lr over the first

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    343 
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    854             else:
    855                 del self._task_info[idx]
--> 856                 return self._process_data(data)
    857 
    858     def _try_put_index(self):

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
    879         self._try_put_index()
    880         if isinstance(data, ExceptionWrapper):
--> 881             data.reraise()
    882         return data
    883 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    392             # (https://bugs.python.org/issue2651), so we work around it.
    393             msg = KeyErrorMessage(msg)
--> 394         raise self.exc_type(msg)

IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/Documents/HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction/Model/Experiments/run_gpu.py", line 52, in __getitem__
    X = self.text[index,:,:]
IndexError: too many indices for array

**Comment by YangLinyi** [comment]
Sorry for the late reply. 

As I lack the whole process in your experiment, I am not sure where is the problem. 

It may be caused by the wrong shape of the index given.
