### ISSUE TITLE
dataset contains 88829 sentences or 576 earning calls' entire text?

### ISSUE THREAD

**Issue by vr25** [YangLinyi/HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction#7]
"HTML: Hierarchical Transformer-based Multi-task Learning for Volatility Prediction" at WWW20.

Dataset:
"These 576 earning calls (instances) correspond to 88,829 aligned sentences (text and audio)."

I just wanted to confirm if you used 88,829 sentences OR just 576 entire text earning calls OR 505 data points (https://github.com/YangLinyi/HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction/blob/master/Data/constituents-financials.csv) as your dataset.

Thank you!

**Comment by YangLinyi** [comment]
It contains 576 transcripts of earnings call which consist of 88,829 sentences. The reason why we have 505 company names in the .csv file is that a single company could have more than one earnings conference over a year.

Hope it answers your question.
