### ISSUE TITLE
lowercase for tfidf baseline?

### ISSUE THREAD

**Issue by vr25** [YangLinyi/HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction#8]
Hi,

Since you've also implemented tf-idf baseline in your paper, just wanted to clarify if you used the exact same text used for Transformer based methods (i.e. without any preprocessing at all) or did you use anything like lowercase, stopword removal, etc for tf-idf (and Transformer-based methods too)?

Thanks!

**Comment by YangLinyi** [comment]
The result of tf-idf method is directly got from [Qin, 19]'s paper. I have not seen the description from their paper, so may you can email to ask them, sorry about that. 

But from my experience, I will remove the stopword first if I use tf-idf as a baseline method.
