### ISSUE TITLE
Degree of voice breaks & standard deviation

### ISSUE THREAD

**Issue by DavidCarlyn** [YangLinyi/HTML-Hierarchical-Transformer-based-Multi-task-Learning-for-Volatility-Prediction#9]
I'm trying to use the same audio feature you used, but I'm a little confused with two of them:

1. Degree of voice breaks (duplicate)
    In the excel sheet with the 27 features: https://drive.google.com/file/d/1dm-hneEZ6O6l_0C0D_qYoqkUbwmZz10v
    Degree of voice breaks is listed twice. What is the difference between the two?
2. Standard Deviation (ambiguous)
    In the same excel sheet, with respect to what property for the standard deviation? Is this just on the spectrum (as referenced in the praat api)?

Thank you!

**Comment by YangLinyi** [comment]
Hi David,

Thanks for your interests. Sorry for the ambiguous description here. 

Our acoustic features are kept as same as [Qin, 19] for a fair comparison. Actually, I have the same issue when I receive the audio features from [Qin, 19]. I remember that they have answered my concerns once time, but a long time ago.  So, maybe you can email them to get the answer (also I will ask them again).

Also, we have collected this kind of data by Praat API by ourself for a much longer period. If you have interests, you can find our dataset and the relevant paper on [here](https://github.com/YangLinyi/MAEC-A-Multimodal-Aligned-Earnings-Conference-Call-Dataset-for-Financial-Risk-Prediction).

Hope it can resolve your questions. Thanks.

**Comment by DavidCarlyn** [comment]
Thank you! I emailed them as well, but waiting for a response. If you find out, posting it here will help me and any others who may ask the same question in the future (with regards to the ambiguous 'Degree of voice breaks').
